import java.util.HashMap;
import java.util.List;

/* Generated By:JJTree: Do not edit this line. ASTArgName.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgName extends SimpleNode {
  public ASTArgName(int id) {
    super(id);
  }

  public ASTArgName(JavaMMParser p, int id) {
    super(p, id);
  }

  public void fillGraph(HashMap<String, LiveNode> graph, List<LiveNode> activeList) {
    String name = this.children[0].toString();
    LiveNode node = new LiveNode(name);

    graph.put(name, node);
    //System.out.println("Adding Main Arg: " + node.varName);
    activeList.add(node);
  }
}
/* JavaCC - OriginalChecksum=994745bc3180a1195cbf126209bfa0f5 (do not edit this line) */
