/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.HashMap;
public
class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(JavaMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String generateCode() {
    Node leftOperand = children[0];
    Node rightOperand = children[1];
    // e.g  a / 4
    if (ASTInteger.isPowerOfTwo(rightOperand)) {
      return leftOperand.generateCode() + ASTInteger.pushLog2(Integer.parseInt(rightOperand.toString())) + "ishr\n";
    }
    return super.generateCode() + "idiv\n";
  }


  public String getType() {
    return "int";
  }


  @Override
  public StackLimitValues calculateStackLimit(StackLimitValues slv){
    return super.calculateStackLimit(slv).decStack(1);
  }

  public boolean isSemanticallyCorrect(HashMap<String, Integer> varInitTable) {
    if(!super.isSemanticallyCorrect(varInitTable))
      return false;
    Node[] children = this.jjtGetChildren();
    Node operator1 = children[0];
    Node operator2 = children[1];

    if(!operator1.getType().equals("int")){
      System.err.println("Error: Left operand of / is not an int. Found: " + operator1.getType() + " at line " + ((SimpleNode)operator1).line + ", column " + ((SimpleNode)operator1).column + ".");
      return false;
    }
    if(!operator2.getType().equals("int")){
      System.err.println("Error: Right operand of / is not an int. Found: " + operator2.getType() + " at line " + ((SimpleNode)operator2).line + ", column " + ((SimpleNode)operator2).column + ".");
      return false;
    }
    return true;
  }

  public Node expressionSimplification() {
    super.expressionSimplification();
    // e.g  0 / var
    if (ASTInteger.isNumber(children[0], 0) && children[1] instanceof ASTIdentifier)
      return new ASTInteger("0");
    // e.g  anything / 0
    if (ASTInteger.isNumber(children[1], 0)) {
      System.err.println("Warning: Division by zero at line " + ((SimpleNode) children[1]).line + ", column " + ((SimpleNode) children[1]).column + ".");
      return this;
    }
    // e.g  anything / 1
    if (ASTInteger.isNumber(children[1], 1))
      return children[0];

    // e.g  var / var
    if (children[0] instanceof ASTIdentifier && children[1] instanceof ASTIdentifier && children[0].toString().equals(children[1].toString()))
      return new ASTInteger("1");


    // e.g  52 / 3
    if (children[0] instanceof ASTInteger && children[1] instanceof ASTInteger)
      return new ASTInteger(String.valueOf(Integer.parseInt(children[0].toString()) / Integer.parseInt(children[1].toString())));
    return this;
  }
}
/* JavaCC - OriginalChecksum=329f52b32e3876a40106077072444b9e (do not edit this line) */
