/* Generated By:JJTree: Do not edit this line. ASTImportName.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportName extends SimpleNode {
  public ASTImportName(int id) {
    super(id);
  }

  public ASTImportName(JavaMMParser p, int id) {
    super(p, id);
  }

  public boolean isMethod = false;

}
/* JavaCC - OriginalChecksum=3bf6d0a8183b9b27f605d6e5cb392456 (do not edit this line) */
