/* Generated By:JJTree: Do not edit this line. ASTImportLifetime.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTImportLifetime extends SimpleNode {
  public ASTImportLifetime(int id) {
    super(id);
  }

  public ASTImportLifetime(JavaMMParser p, int id) {
    super(p, id);
  }

  public boolean isStatic = false;

}
/* JavaCC - OriginalChecksum=4c03a82acae0d11e385beb7824b1f1f7 (do not edit this line) */
