/* Generated By:JJTree: Do not edit this line. ASTLength.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTLength extends SimpleNode {
  @Override
  public String toString() {
    return "length";
  }

  public ASTLength(int id) {
    super(id);
  }

  public ASTLength(JavaMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=172387562c43a0fdf63e5644dfe17d7f (do not edit this line) */
