/* Generated By:JJTree: Do not edit this line. ASTMethodContent.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodContent extends SimpleNode {
  public ASTMethodContent(int id) {
    super(id);
  }

  public ASTMethodContent(JavaMMParser p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=5935062df4b833c2c80c4fc58ff057c5 (do not edit this line) */
