import java.util.HashMap;
import java.util.List;

/* Generated By:JJTree: Do not edit this line. ASTObjectInitArgs.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTObjectInitArgs extends SimpleNode {
  public ASTObjectInitArgs(int id) {
    super(id);
  }

  public ASTObjectInitArgs(JavaMMParser p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=018dc07eae3b0cfefa9c401313e09a0e (do not edit this line) */
