/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(JavaMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String generateCode() {
    return super.generateCode() + generateReturn(this.children[0]);
  }

  @Override
  public StackLimitValues calculateStackLimit(StackLimitValues slv){
    return super.calculateStackLimit(slv).decStack(1);
  }

  private String generateReturn(Node node) {
    switch (node.getType()) {
      case "int": return "ireturn\n";
      case "boolean": return "ireturn\n";
      default: return "areturn\n";
    }
  }



}
/* JavaCC - OriginalChecksum=0ce5e1598661bb332238aee6815b2a51 (do not edit this line) */
